// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/playgangneung/Feed.tsx": () => import("../components/mockups/playgangneung/Feed.tsx"),
  "./components/mockups/playgangneung/Story.tsx": () => import("../components/mockups/playgangneung/Story.tsx"),
  "./components/mockups/playgangneung/Video.tsx": () => import("../components/mockups/playgangneung/Video.tsx")
};
